/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CbpButton {
    }
}
declare global {
    interface HTMLCbpButtonElement extends Components.CbpButton, HTMLStencilElement {
    }
    var HTMLCbpButtonElement: {
        prototype: HTMLCbpButtonElement;
        new (): HTMLCbpButtonElement;
    };
    interface HTMLElementTagNameMap {
        "cbp-button": HTMLCbpButtonElement;
    }
}
declare namespace LocalJSX {
    interface CbpButton {
    }
    interface IntrinsicElements {
        "cbp-button": CbpButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cbp-button": LocalJSX.CbpButton & JSXBase.HTMLAttributes<HTMLCbpButtonElement>;
        }
    }
}
