'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { CbpAccordionItem as CbpAccordionItemElement, defineCustomElement as defineCbpAccordionItem } from "@cbpds/web-components/dist/components/cbp-accordion-item.js";
import { CbpAccordion as CbpAccordionElement, defineCustomElement as defineCbpAccordion } from "@cbpds/web-components/dist/components/cbp-accordion.js";
import { CbpActionBar as CbpActionBarElement, defineCustomElement as defineCbpActionBar } from "@cbpds/web-components/dist/components/cbp-action-bar.js";
import { CbpAppHeader as CbpAppHeaderElement, defineCustomElement as defineCbpAppHeader } from "@cbpds/web-components/dist/components/cbp-app-header.js";
import { CbpApp as CbpAppElement, defineCustomElement as defineCbpApp } from "@cbpds/web-components/dist/components/cbp-app.js";
import { CbpBadge as CbpBadgeElement, defineCustomElement as defineCbpBadge } from "@cbpds/web-components/dist/components/cbp-badge.js";
import { CbpBanner as CbpBannerElement, defineCustomElement as defineCbpBanner } from "@cbpds/web-components/dist/components/cbp-banner.js";
import { CbpBreadcrumb as CbpBreadcrumbElement, defineCustomElement as defineCbpBreadcrumb } from "@cbpds/web-components/dist/components/cbp-breadcrumb.js";
import { CbpButton as CbpButtonElement, defineCustomElement as defineCbpButton } from "@cbpds/web-components/dist/components/cbp-button.js";
import { CbpCard as CbpCardElement, defineCustomElement as defineCbpCard } from "@cbpds/web-components/dist/components/cbp-card.js";
import { CbpCheckbox as CbpCheckboxElement, defineCustomElement as defineCbpCheckbox } from "@cbpds/web-components/dist/components/cbp-checkbox.js";
import { CbpChip as CbpChipElement, defineCustomElement as defineCbpChip } from "@cbpds/web-components/dist/components/cbp-chip.js";
import { CbpContainer as CbpContainerElement, defineCustomElement as defineCbpContainer } from "@cbpds/web-components/dist/components/cbp-container.js";
import { CbpDialog as CbpDialogElement, defineCustomElement as defineCbpDialog } from "@cbpds/web-components/dist/components/cbp-dialog.js";
import { CbpDrawer as CbpDrawerElement, defineCustomElement as defineCbpDrawer } from "@cbpds/web-components/dist/components/cbp-drawer.js";
import { CbpDropdownItem as CbpDropdownItemElement, defineCustomElement as defineCbpDropdownItem } from "@cbpds/web-components/dist/components/cbp-dropdown-item.js";
import { CbpDropdown as CbpDropdownElement, defineCustomElement as defineCbpDropdown } from "@cbpds/web-components/dist/components/cbp-dropdown.js";
import { CbpExpand as CbpExpandElement, defineCustomElement as defineCbpExpand } from "@cbpds/web-components/dist/components/cbp-expand.js";
import { CbpFileInput as CbpFileInputElement, defineCustomElement as defineCbpFileInput } from "@cbpds/web-components/dist/components/cbp-file-input.js";
import { CbpFlexItem as CbpFlexItemElement, defineCustomElement as defineCbpFlexItem } from "@cbpds/web-components/dist/components/cbp-flex-item.js";
import { CbpFlex as CbpFlexElement, defineCustomElement as defineCbpFlex } from "@cbpds/web-components/dist/components/cbp-flex.js";
import { CbpFooter as CbpFooterElement, defineCustomElement as defineCbpFooter } from "@cbpds/web-components/dist/components/cbp-footer.js";
import { CbpFormFieldWrapper as CbpFormFieldWrapperElement, defineCustomElement as defineCbpFormFieldWrapper } from "@cbpds/web-components/dist/components/cbp-form-field-wrapper.js";
import { CbpFormField as CbpFormFieldElement, defineCustomElement as defineCbpFormField } from "@cbpds/web-components/dist/components/cbp-form-field.js";
import { CbpGridItem as CbpGridItemElement, defineCustomElement as defineCbpGridItem } from "@cbpds/web-components/dist/components/cbp-grid-item.js";
import { CbpGrid as CbpGridElement, defineCustomElement as defineCbpGrid } from "@cbpds/web-components/dist/components/cbp-grid.js";
import { CbpHide as CbpHideElement, defineCustomElement as defineCbpHide } from "@cbpds/web-components/dist/components/cbp-hide.js";
import { CbpIcon as CbpIconElement, defineCustomElement as defineCbpIcon } from "@cbpds/web-components/dist/components/cbp-icon.js";
import { CbpLink as CbpLinkElement, defineCustomElement as defineCbpLink } from "@cbpds/web-components/dist/components/cbp-link.js";
import { CbpList as CbpListElement, defineCustomElement as defineCbpList } from "@cbpds/web-components/dist/components/cbp-list.js";
import { CbpLoader as CbpLoaderElement, defineCustomElement as defineCbpLoader } from "@cbpds/web-components/dist/components/cbp-loader.js";
import { CbpMulticol as CbpMulticolElement, defineCustomElement as defineCbpMulticol } from "@cbpds/web-components/dist/components/cbp-multicol.js";
import { CbpNavItem as CbpNavItemElement, defineCustomElement as defineCbpNavItem } from "@cbpds/web-components/dist/components/cbp-nav-item.js";
import { CbpNotice as CbpNoticeElement, defineCustomElement as defineCbpNotice } from "@cbpds/web-components/dist/components/cbp-notice.js";
import { CbpPagination as CbpPaginationElement, defineCustomElement as defineCbpPagination } from "@cbpds/web-components/dist/components/cbp-pagination.js";
import { CbpPanel as CbpPanelElement, defineCustomElement as defineCbpPanel } from "@cbpds/web-components/dist/components/cbp-panel.js";
import { CbpRadio as CbpRadioElement, defineCustomElement as defineCbpRadio } from "@cbpds/web-components/dist/components/cbp-radio.js";
import { CbpResizeObserver as CbpResizeObserverElement, defineCustomElement as defineCbpResizeObserver } from "@cbpds/web-components/dist/components/cbp-resize-observer.js";
import { CbpSection as CbpSectionElement, defineCustomElement as defineCbpSection } from "@cbpds/web-components/dist/components/cbp-section.js";
import { CbpSegmentedButtonGroup as CbpSegmentedButtonGroupElement, defineCustomElement as defineCbpSegmentedButtonGroup } from "@cbpds/web-components/dist/components/cbp-segmented-button-group.js";
import { CbpSkipNav as CbpSkipNavElement, defineCustomElement as defineCbpSkipNav } from "@cbpds/web-components/dist/components/cbp-skip-nav.js";
import { CbpStructuredListItem as CbpStructuredListItemElement, defineCustomElement as defineCbpStructuredListItem } from "@cbpds/web-components/dist/components/cbp-structured-list-item.js";
import { CbpStructuredList as CbpStructuredListElement, defineCustomElement as defineCbpStructuredList } from "@cbpds/web-components/dist/components/cbp-structured-list.js";
import { CbpSubnavItem as CbpSubnavItemElement, defineCustomElement as defineCbpSubnavItem } from "@cbpds/web-components/dist/components/cbp-subnav-item.js";
import { CbpSubnav as CbpSubnavElement, defineCustomElement as defineCbpSubnav } from "@cbpds/web-components/dist/components/cbp-subnav.js";
import { CbpTabPanel as CbpTabPanelElement, defineCustomElement as defineCbpTabPanel } from "@cbpds/web-components/dist/components/cbp-tab-panel.js";
import { CbpTab as CbpTabElement, defineCustomElement as defineCbpTab } from "@cbpds/web-components/dist/components/cbp-tab.js";
import { CbpTable as CbpTableElement, defineCustomElement as defineCbpTable } from "@cbpds/web-components/dist/components/cbp-table.js";
import { CbpTabs as CbpTabsElement, defineCustomElement as defineCbpTabs } from "@cbpds/web-components/dist/components/cbp-tabs.js";
import { CbpTag as CbpTagElement, defineCustomElement as defineCbpTag } from "@cbpds/web-components/dist/components/cbp-tag.js";
import { CbpToast as CbpToastElement, defineCustomElement as defineCbpToast } from "@cbpds/web-components/dist/components/cbp-toast.js";
import { CbpToggle as CbpToggleElement, defineCustomElement as defineCbpToggle } from "@cbpds/web-components/dist/components/cbp-toggle.js";
import { CbpTooltip as CbpTooltipElement, defineCustomElement as defineCbpTooltip } from "@cbpds/web-components/dist/components/cbp-tooltip.js";
import { CbpTypography as CbpTypographyElement, defineCustomElement as defineCbpTypography } from "@cbpds/web-components/dist/components/cbp-typography.js";
import { CbpUniversalHeader as CbpUniversalHeaderElement, defineCustomElement as defineCbpUniversalHeader } from "@cbpds/web-components/dist/components/cbp-universal-header.js";
import { CbpUsaBanner as CbpUsaBannerElement, defineCustomElement as defineCbpUsaBanner } from "@cbpds/web-components/dist/components/cbp-usa-banner.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type CbpAccordionEvents = NonNullable<unknown>;

export const CbpAccordion: StencilReactComponent<CbpAccordionElement, CbpAccordionEvents> = /*@__PURE__*/ createComponent<CbpAccordionElement, CbpAccordionEvents>({
    tagName: 'cbp-accordion',
    elementClass: CbpAccordionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpAccordionEvents,
    defineCustomElement: defineCbpAccordion
});

type CbpAccordionItemEvents = { onAccordionItemClick: EventName<CustomEvent<any>> };

export const CbpAccordionItem: StencilReactComponent<CbpAccordionItemElement, CbpAccordionItemEvents> = /*@__PURE__*/ createComponent<CbpAccordionItemElement, CbpAccordionItemEvents>({
    tagName: 'cbp-accordion-item',
    elementClass: CbpAccordionItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onAccordionItemClick: 'accordionItemClick' } as CbpAccordionItemEvents,
    defineCustomElement: defineCbpAccordionItem
});

type CbpActionBarEvents = NonNullable<unknown>;

export const CbpActionBar: StencilReactComponent<CbpActionBarElement, CbpActionBarEvents> = /*@__PURE__*/ createComponent<CbpActionBarElement, CbpActionBarEvents>({
    tagName: 'cbp-action-bar',
    elementClass: CbpActionBarElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpActionBarEvents,
    defineCustomElement: defineCbpActionBar
});

type CbpAppEvents = NonNullable<unknown>;

export const CbpApp: StencilReactComponent<CbpAppElement, CbpAppEvents> = /*@__PURE__*/ createComponent<CbpAppElement, CbpAppEvents>({
    tagName: 'cbp-app',
    elementClass: CbpAppElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpAppEvents,
    defineCustomElement: defineCbpApp
});

type CbpAppHeaderEvents = NonNullable<unknown>;

export const CbpAppHeader: StencilReactComponent<CbpAppHeaderElement, CbpAppHeaderEvents> = /*@__PURE__*/ createComponent<CbpAppHeaderElement, CbpAppHeaderEvents>({
    tagName: 'cbp-app-header',
    elementClass: CbpAppHeaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpAppHeaderEvents,
    defineCustomElement: defineCbpAppHeader
});

type CbpBadgeEvents = NonNullable<unknown>;

export const CbpBadge: StencilReactComponent<CbpBadgeElement, CbpBadgeEvents> = /*@__PURE__*/ createComponent<CbpBadgeElement, CbpBadgeEvents>({
    tagName: 'cbp-badge',
    elementClass: CbpBadgeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpBadgeEvents,
    defineCustomElement: defineCbpBadge
});

type CbpBannerEvents = { onBannerDismiss: EventName<CustomEvent<any>> };

export const CbpBanner: StencilReactComponent<CbpBannerElement, CbpBannerEvents> = /*@__PURE__*/ createComponent<CbpBannerElement, CbpBannerEvents>({
    tagName: 'cbp-banner',
    elementClass: CbpBannerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onBannerDismiss: 'bannerDismiss' } as CbpBannerEvents,
    defineCustomElement: defineCbpBanner
});

type CbpBreadcrumbEvents = NonNullable<unknown>;

export const CbpBreadcrumb: StencilReactComponent<CbpBreadcrumbElement, CbpBreadcrumbEvents> = /*@__PURE__*/ createComponent<CbpBreadcrumbElement, CbpBreadcrumbEvents>({
    tagName: 'cbp-breadcrumb',
    elementClass: CbpBreadcrumbElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpBreadcrumbEvents,
    defineCustomElement: defineCbpBreadcrumb
});

type CbpButtonEvents = {
    onButtonClick: EventName<CustomEvent<any>>,
    onComponentLoad: EventName<CustomEvent<any>>
};

export const CbpButton: StencilReactComponent<CbpButtonElement, CbpButtonEvents> = /*@__PURE__*/ createComponent<CbpButtonElement, CbpButtonEvents>({
    tagName: 'cbp-button',
    elementClass: CbpButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onButtonClick: 'buttonClick',
        onComponentLoad: 'componentLoad'
    } as CbpButtonEvents,
    defineCustomElement: defineCbpButton
});

type CbpCardEvents = NonNullable<unknown>;

export const CbpCard: StencilReactComponent<CbpCardElement, CbpCardEvents> = /*@__PURE__*/ createComponent<CbpCardElement, CbpCardEvents>({
    tagName: 'cbp-card',
    elementClass: CbpCardElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpCardEvents,
    defineCustomElement: defineCbpCard
});

type CbpCheckboxEvents = { onStateChanged: EventName<CustomEvent<any>> };

export const CbpCheckbox: StencilReactComponent<CbpCheckboxElement, CbpCheckboxEvents> = /*@__PURE__*/ createComponent<CbpCheckboxElement, CbpCheckboxEvents>({
    tagName: 'cbp-checkbox',
    elementClass: CbpCheckboxElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onStateChanged: 'stateChanged' } as CbpCheckboxEvents,
    defineCustomElement: defineCbpCheckbox
});

type CbpChipEvents = { onChipClick: EventName<CustomEvent<any>> };

export const CbpChip: StencilReactComponent<CbpChipElement, CbpChipEvents> = /*@__PURE__*/ createComponent<CbpChipElement, CbpChipEvents>({
    tagName: 'cbp-chip',
    elementClass: CbpChipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onChipClick: 'chipClick' } as CbpChipEvents,
    defineCustomElement: defineCbpChip
});

type CbpContainerEvents = NonNullable<unknown>;

export const CbpContainer: StencilReactComponent<CbpContainerElement, CbpContainerEvents> = /*@__PURE__*/ createComponent<CbpContainerElement, CbpContainerEvents>({
    tagName: 'cbp-container',
    elementClass: CbpContainerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpContainerEvents,
    defineCustomElement: defineCbpContainer
});

type CbpDialogEvents = {
    onDialogOpen: EventName<CustomEvent<any>>,
    onDialogClose: EventName<CustomEvent<any>>
};

export const CbpDialog: StencilReactComponent<CbpDialogElement, CbpDialogEvents> = /*@__PURE__*/ createComponent<CbpDialogElement, CbpDialogEvents>({
    tagName: 'cbp-dialog',
    elementClass: CbpDialogElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onDialogOpen: 'dialogOpen',
        onDialogClose: 'dialogClose'
    } as CbpDialogEvents,
    defineCustomElement: defineCbpDialog
});

type CbpDrawerEvents = {
    onDrawerOpen: EventName<CustomEvent<any>>,
    onDrawerClose: EventName<CustomEvent<any>>
};

export const CbpDrawer: StencilReactComponent<CbpDrawerElement, CbpDrawerEvents> = /*@__PURE__*/ createComponent<CbpDrawerElement, CbpDrawerEvents>({
    tagName: 'cbp-drawer',
    elementClass: CbpDrawerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onDrawerOpen: 'drawerOpen',
        onDrawerClose: 'drawerClose'
    } as CbpDrawerEvents,
    defineCustomElement: defineCbpDrawer
});

type CbpDropdownEvents = { onValueChange: EventName<CustomEvent<any>> };

export const CbpDropdown: StencilReactComponent<CbpDropdownElement, CbpDropdownEvents> = /*@__PURE__*/ createComponent<CbpDropdownElement, CbpDropdownEvents>({
    tagName: 'cbp-dropdown',
    elementClass: CbpDropdownElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onValueChange: 'valueChange' } as CbpDropdownEvents,
    defineCustomElement: defineCbpDropdown
});

type CbpDropdownItemEvents = { onDropdownItemClick: EventName<CustomEvent<any>> };

export const CbpDropdownItem: StencilReactComponent<CbpDropdownItemElement, CbpDropdownItemEvents> = /*@__PURE__*/ createComponent<CbpDropdownItemElement, CbpDropdownItemEvents>({
    tagName: 'cbp-dropdown-item',
    elementClass: CbpDropdownItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onDropdownItemClick: 'dropdownItemClick' } as CbpDropdownItemEvents,
    defineCustomElement: defineCbpDropdownItem
});

type CbpExpandEvents = { onExpandClick: EventName<CustomEvent<any>> };

export const CbpExpand: StencilReactComponent<CbpExpandElement, CbpExpandEvents> = /*@__PURE__*/ createComponent<CbpExpandElement, CbpExpandEvents>({
    tagName: 'cbp-expand',
    elementClass: CbpExpandElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onExpandClick: 'expandClick' } as CbpExpandEvents,
    defineCustomElement: defineCbpExpand
});

type CbpFileInputEvents = { onValueChange: EventName<CustomEvent<any>> };

export const CbpFileInput: StencilReactComponent<CbpFileInputElement, CbpFileInputEvents> = /*@__PURE__*/ createComponent<CbpFileInputElement, CbpFileInputEvents>({
    tagName: 'cbp-file-input',
    elementClass: CbpFileInputElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onValueChange: 'valueChange' } as CbpFileInputEvents,
    defineCustomElement: defineCbpFileInput
});

type CbpFlexEvents = NonNullable<unknown>;

export const CbpFlex: StencilReactComponent<CbpFlexElement, CbpFlexEvents> = /*@__PURE__*/ createComponent<CbpFlexElement, CbpFlexEvents>({
    tagName: 'cbp-flex',
    elementClass: CbpFlexElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpFlexEvents,
    defineCustomElement: defineCbpFlex
});

type CbpFlexItemEvents = NonNullable<unknown>;

export const CbpFlexItem: StencilReactComponent<CbpFlexItemElement, CbpFlexItemEvents> = /*@__PURE__*/ createComponent<CbpFlexItemElement, CbpFlexItemEvents>({
    tagName: 'cbp-flex-item',
    elementClass: CbpFlexItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpFlexItemEvents,
    defineCustomElement: defineCbpFlexItem
});

type CbpFooterEvents = NonNullable<unknown>;

export const CbpFooter: StencilReactComponent<CbpFooterElement, CbpFooterEvents> = /*@__PURE__*/ createComponent<CbpFooterElement, CbpFooterEvents>({
    tagName: 'cbp-footer',
    elementClass: CbpFooterElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpFooterEvents,
    defineCustomElement: defineCbpFooter
});

type CbpFormFieldEvents = { onValueChange: EventName<CustomEvent<any>> };

export const CbpFormField: StencilReactComponent<CbpFormFieldElement, CbpFormFieldEvents> = /*@__PURE__*/ createComponent<CbpFormFieldElement, CbpFormFieldEvents>({
    tagName: 'cbp-form-field',
    elementClass: CbpFormFieldElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onValueChange: 'valueChange' } as CbpFormFieldEvents,
    defineCustomElement: defineCbpFormField
});

type CbpFormFieldWrapperEvents = NonNullable<unknown>;

export const CbpFormFieldWrapper: StencilReactComponent<CbpFormFieldWrapperElement, CbpFormFieldWrapperEvents> = /*@__PURE__*/ createComponent<CbpFormFieldWrapperElement, CbpFormFieldWrapperEvents>({
    tagName: 'cbp-form-field-wrapper',
    elementClass: CbpFormFieldWrapperElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpFormFieldWrapperEvents,
    defineCustomElement: defineCbpFormFieldWrapper
});

type CbpGridEvents = NonNullable<unknown>;

export const CbpGrid: StencilReactComponent<CbpGridElement, CbpGridEvents> = /*@__PURE__*/ createComponent<CbpGridElement, CbpGridEvents>({
    tagName: 'cbp-grid',
    elementClass: CbpGridElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpGridEvents,
    defineCustomElement: defineCbpGrid
});

type CbpGridItemEvents = NonNullable<unknown>;

export const CbpGridItem: StencilReactComponent<CbpGridItemElement, CbpGridItemEvents> = /*@__PURE__*/ createComponent<CbpGridItemElement, CbpGridItemEvents>({
    tagName: 'cbp-grid-item',
    elementClass: CbpGridItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpGridItemEvents,
    defineCustomElement: defineCbpGridItem
});

type CbpHideEvents = { onHideToggle: EventName<CustomEvent<any>> };

export const CbpHide: StencilReactComponent<CbpHideElement, CbpHideEvents> = /*@__PURE__*/ createComponent<CbpHideElement, CbpHideEvents>({
    tagName: 'cbp-hide',
    elementClass: CbpHideElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onHideToggle: 'hideToggle' } as CbpHideEvents,
    defineCustomElement: defineCbpHide
});

type CbpIconEvents = NonNullable<unknown>;

export const CbpIcon: StencilReactComponent<CbpIconElement, CbpIconEvents> = /*@__PURE__*/ createComponent<CbpIconElement, CbpIconEvents>({
    tagName: 'cbp-icon',
    elementClass: CbpIconElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpIconEvents,
    defineCustomElement: defineCbpIcon
});

type CbpLinkEvents = { onLinkClick: EventName<CustomEvent<any>> };

export const CbpLink: StencilReactComponent<CbpLinkElement, CbpLinkEvents> = /*@__PURE__*/ createComponent<CbpLinkElement, CbpLinkEvents>({
    tagName: 'cbp-link',
    elementClass: CbpLinkElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onLinkClick: 'linkClick' } as CbpLinkEvents,
    defineCustomElement: defineCbpLink
});

type CbpListEvents = NonNullable<unknown>;

export const CbpList: StencilReactComponent<CbpListElement, CbpListEvents> = /*@__PURE__*/ createComponent<CbpListElement, CbpListEvents>({
    tagName: 'cbp-list',
    elementClass: CbpListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpListEvents,
    defineCustomElement: defineCbpList
});

type CbpLoaderEvents = NonNullable<unknown>;

export const CbpLoader: StencilReactComponent<CbpLoaderElement, CbpLoaderEvents> = /*@__PURE__*/ createComponent<CbpLoaderElement, CbpLoaderEvents>({
    tagName: 'cbp-loader',
    elementClass: CbpLoaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpLoaderEvents,
    defineCustomElement: defineCbpLoader
});

type CbpMulticolEvents = NonNullable<unknown>;

export const CbpMulticol: StencilReactComponent<CbpMulticolElement, CbpMulticolEvents> = /*@__PURE__*/ createComponent<CbpMulticolElement, CbpMulticolEvents>({
    tagName: 'cbp-multicol',
    elementClass: CbpMulticolElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpMulticolEvents,
    defineCustomElement: defineCbpMulticol
});

type CbpNavItemEvents = { onNavClicked: EventName<CustomEvent<any>> };

export const CbpNavItem: StencilReactComponent<CbpNavItemElement, CbpNavItemEvents> = /*@__PURE__*/ createComponent<CbpNavItemElement, CbpNavItemEvents>({
    tagName: 'cbp-nav-item',
    elementClass: CbpNavItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onNavClicked: 'navClicked' } as CbpNavItemEvents,
    defineCustomElement: defineCbpNavItem
});

type CbpNoticeEvents = NonNullable<unknown>;

export const CbpNotice: StencilReactComponent<CbpNoticeElement, CbpNoticeEvents> = /*@__PURE__*/ createComponent<CbpNoticeElement, CbpNoticeEvents>({
    tagName: 'cbp-notice',
    elementClass: CbpNoticeElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpNoticeEvents,
    defineCustomElement: defineCbpNotice
});

type CbpPaginationEvents = { onPaginationChange: EventName<CustomEvent<any>> };

export const CbpPagination: StencilReactComponent<CbpPaginationElement, CbpPaginationEvents> = /*@__PURE__*/ createComponent<CbpPaginationElement, CbpPaginationEvents>({
    tagName: 'cbp-pagination',
    elementClass: CbpPaginationElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onPaginationChange: 'paginationChange' } as CbpPaginationEvents,
    defineCustomElement: defineCbpPagination
});

type CbpPanelEvents = NonNullable<unknown>;

export const CbpPanel: StencilReactComponent<CbpPanelElement, CbpPanelEvents> = /*@__PURE__*/ createComponent<CbpPanelElement, CbpPanelEvents>({
    tagName: 'cbp-panel',
    elementClass: CbpPanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpPanelEvents,
    defineCustomElement: defineCbpPanel
});

type CbpRadioEvents = { onStateChanged: EventName<CustomEvent<any>> };

export const CbpRadio: StencilReactComponent<CbpRadioElement, CbpRadioEvents> = /*@__PURE__*/ createComponent<CbpRadioElement, CbpRadioEvents>({
    tagName: 'cbp-radio',
    elementClass: CbpRadioElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onStateChanged: 'stateChanged' } as CbpRadioEvents,
    defineCustomElement: defineCbpRadio
});

type CbpResizeObserverEvents = { onResized: EventName<CustomEvent<any>> };

export const CbpResizeObserver: StencilReactComponent<CbpResizeObserverElement, CbpResizeObserverEvents> = /*@__PURE__*/ createComponent<CbpResizeObserverElement, CbpResizeObserverEvents>({
    tagName: 'cbp-resize-observer',
    elementClass: CbpResizeObserverElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onResized: 'resized' } as CbpResizeObserverEvents,
    defineCustomElement: defineCbpResizeObserver
});

type CbpSectionEvents = NonNullable<unknown>;

export const CbpSection: StencilReactComponent<CbpSectionElement, CbpSectionEvents> = /*@__PURE__*/ createComponent<CbpSectionElement, CbpSectionEvents>({
    tagName: 'cbp-section',
    elementClass: CbpSectionElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpSectionEvents,
    defineCustomElement: defineCbpSection
});

type CbpSegmentedButtonGroupEvents = { onSegmentedButtonGroupClick: EventName<CustomEvent<any>> };

export const CbpSegmentedButtonGroup: StencilReactComponent<CbpSegmentedButtonGroupElement, CbpSegmentedButtonGroupEvents> = /*@__PURE__*/ createComponent<CbpSegmentedButtonGroupElement, CbpSegmentedButtonGroupEvents>({
    tagName: 'cbp-segmented-button-group',
    elementClass: CbpSegmentedButtonGroupElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onSegmentedButtonGroupClick: 'segmentedButtonGroupClick' } as CbpSegmentedButtonGroupEvents,
    defineCustomElement: defineCbpSegmentedButtonGroup
});

type CbpSkipNavEvents = NonNullable<unknown>;

export const CbpSkipNav: StencilReactComponent<CbpSkipNavElement, CbpSkipNavEvents> = /*@__PURE__*/ createComponent<CbpSkipNavElement, CbpSkipNavEvents>({
    tagName: 'cbp-skip-nav',
    elementClass: CbpSkipNavElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpSkipNavEvents,
    defineCustomElement: defineCbpSkipNav
});

type CbpStructuredListEvents = NonNullable<unknown>;

export const CbpStructuredList: StencilReactComponent<CbpStructuredListElement, CbpStructuredListEvents> = /*@__PURE__*/ createComponent<CbpStructuredListElement, CbpStructuredListEvents>({
    tagName: 'cbp-structured-list',
    elementClass: CbpStructuredListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpStructuredListEvents,
    defineCustomElement: defineCbpStructuredList
});

type CbpStructuredListItemEvents = NonNullable<unknown>;

export const CbpStructuredListItem: StencilReactComponent<CbpStructuredListItemElement, CbpStructuredListItemEvents> = /*@__PURE__*/ createComponent<CbpStructuredListItemElement, CbpStructuredListItemEvents>({
    tagName: 'cbp-structured-list-item',
    elementClass: CbpStructuredListItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpStructuredListItemEvents,
    defineCustomElement: defineCbpStructuredListItem
});

type CbpSubnavEvents = NonNullable<unknown>;

export const CbpSubnav: StencilReactComponent<CbpSubnavElement, CbpSubnavEvents> = /*@__PURE__*/ createComponent<CbpSubnavElement, CbpSubnavEvents>({
    tagName: 'cbp-subnav',
    elementClass: CbpSubnavElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpSubnavEvents,
    defineCustomElement: defineCbpSubnav
});

type CbpSubnavItemEvents = { onToggleSubnavClick: EventName<CustomEvent<any>> };

export const CbpSubnavItem: StencilReactComponent<CbpSubnavItemElement, CbpSubnavItemEvents> = /*@__PURE__*/ createComponent<CbpSubnavItemElement, CbpSubnavItemEvents>({
    tagName: 'cbp-subnav-item',
    elementClass: CbpSubnavItemElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onToggleSubnavClick: 'toggleSubnavClick' } as CbpSubnavItemEvents,
    defineCustomElement: defineCbpSubnavItem
});

type CbpTabEvents = {
    onTabLoaded: EventName<CustomEvent<any>>,
    onTabClicked: EventName<CustomEvent<any>>
};

export const CbpTab: StencilReactComponent<CbpTabElement, CbpTabEvents> = /*@__PURE__*/ createComponent<CbpTabElement, CbpTabEvents>({
    tagName: 'cbp-tab',
    elementClass: CbpTabElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {
        onTabLoaded: 'tabLoaded',
        onTabClicked: 'tabClicked'
    } as CbpTabEvents,
    defineCustomElement: defineCbpTab
});

type CbpTabPanelEvents = NonNullable<unknown>;

export const CbpTabPanel: StencilReactComponent<CbpTabPanelElement, CbpTabPanelEvents> = /*@__PURE__*/ createComponent<CbpTabPanelElement, CbpTabPanelEvents>({
    tagName: 'cbp-tab-panel',
    elementClass: CbpTabPanelElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpTabPanelEvents,
    defineCustomElement: defineCbpTabPanel
});

type CbpTableEvents = { onTablesorted: EventName<CustomEvent<any>> };

export const CbpTable: StencilReactComponent<CbpTableElement, CbpTableEvents> = /*@__PURE__*/ createComponent<CbpTableElement, CbpTableEvents>({
    tagName: 'cbp-table',
    elementClass: CbpTableElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onTablesorted: 'tablesorted' } as CbpTableEvents,
    defineCustomElement: defineCbpTable
});

type CbpTabsEvents = NonNullable<unknown>;

export const CbpTabs: StencilReactComponent<CbpTabsElement, CbpTabsEvents> = /*@__PURE__*/ createComponent<CbpTabsElement, CbpTabsEvents>({
    tagName: 'cbp-tabs',
    elementClass: CbpTabsElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpTabsEvents,
    defineCustomElement: defineCbpTabs
});

type CbpTagEvents = NonNullable<unknown>;

export const CbpTag: StencilReactComponent<CbpTagElement, CbpTagEvents> = /*@__PURE__*/ createComponent<CbpTagElement, CbpTagEvents>({
    tagName: 'cbp-tag',
    elementClass: CbpTagElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpTagEvents,
    defineCustomElement: defineCbpTag
});

type CbpToastEvents = NonNullable<unknown>;

export const CbpToast: StencilReactComponent<CbpToastElement, CbpToastEvents> = /*@__PURE__*/ createComponent<CbpToastElement, CbpToastEvents>({
    tagName: 'cbp-toast',
    elementClass: CbpToastElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpToastEvents,
    defineCustomElement: defineCbpToast
});

type CbpToggleEvents = { onToggleClick: EventName<CustomEvent<any>> };

export const CbpToggle: StencilReactComponent<CbpToggleElement, CbpToggleEvents> = /*@__PURE__*/ createComponent<CbpToggleElement, CbpToggleEvents>({
    tagName: 'cbp-toggle',
    elementClass: CbpToggleElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onToggleClick: 'toggleClick' } as CbpToggleEvents,
    defineCustomElement: defineCbpToggle
});

type CbpTooltipEvents = NonNullable<unknown>;

export const CbpTooltip: StencilReactComponent<CbpTooltipElement, CbpTooltipEvents> = /*@__PURE__*/ createComponent<CbpTooltipElement, CbpTooltipEvents>({
    tagName: 'cbp-tooltip',
    elementClass: CbpTooltipElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpTooltipEvents,
    defineCustomElement: defineCbpTooltip
});

type CbpTypographyEvents = NonNullable<unknown>;

export const CbpTypography: StencilReactComponent<CbpTypographyElement, CbpTypographyEvents> = /*@__PURE__*/ createComponent<CbpTypographyElement, CbpTypographyEvents>({
    tagName: 'cbp-typography',
    elementClass: CbpTypographyElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpTypographyEvents,
    defineCustomElement: defineCbpTypography
});

type CbpUniversalHeaderEvents = NonNullable<unknown>;

export const CbpUniversalHeader: StencilReactComponent<CbpUniversalHeaderElement, CbpUniversalHeaderEvents> = /*@__PURE__*/ createComponent<CbpUniversalHeaderElement, CbpUniversalHeaderEvents>({
    tagName: 'cbp-universal-header',
    elementClass: CbpUniversalHeaderElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpUniversalHeaderEvents,
    defineCustomElement: defineCbpUniversalHeader
});

type CbpUsaBannerEvents = NonNullable<unknown>;

export const CbpUsaBanner: StencilReactComponent<CbpUsaBannerElement, CbpUsaBannerEvents> = /*@__PURE__*/ createComponent<CbpUsaBannerElement, CbpUsaBannerEvents>({
    tagName: 'cbp-usa-banner',
    elementClass: CbpUsaBannerElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as CbpUsaBannerEvents,
    defineCustomElement: defineCbpUsaBanner
});
